name: Typeset presentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: gqcg-oss/latex-action@master
      with:
        root_file: presentation.tex
        working_directory: theory/presentation
        latexmk_use_xelatex: true
    
    - name: Archive presentation for main
      uses: actions/upload-artifact@v2
      with:
        name: presentation.pdf
        path: theory/presentation/presentation.pdf
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    - name: Archive presentation for PR
      uses: actions/upload-artifact@v2
      with:
        name: presentation.pdf
        path: theory/presentation/presentation.pdf
        retention-days: 5
      if: ${{ github.event_name == 'pull_request'}}
      
